### PR TITLE
Add pr-preview file

### PR DESCRIPTION
**Pull request by anssiko**
@tobie is enabling really this easy if the integration is installed?

### CODE REVIEW

**Comment by tobie** [comment]
Yes. Did you use the tool to create the pr?

**Comment by tobie** [comment]
(Just curious, it doesn't change anything)

**Comment by anssiko** [comment]
Cool. No, crafted the PR as usual. Will land this to w3c org now, closing this.

**Comment by tobie** [comment]
https://tobie.github.io/pr-preview/config.html

**Comment by anssiko** [comment]
Wow, even easier :) I missed the "config page" link in the docs initially.

**Pull request closed without merging**
